<table class="disclaimer"><tr><td>
<a href="directory.html" class="adisclaimer">Directory</a>
&#8226;
<a href="disclaimer.html" class="adisclaimer">National Disclaimer</a>
&#8226;
<a href="tos.html" class="adisclaimer">Terms of Service</a>
&#8226;
<a href="privacy.html" class="adisclaimer">Privacy Policy</a>
&#8226;
<a href="#" id="webchairMail" class="adisclaimer">Contact Webchair</a>
&#8226;
<a href="contact.html" class="adisclaimer">Contact OI</a>
</td></tr></table>

<br>